# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serial/serial.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='serial/serial.proto',
  package='coralreef.api.serial',
  syntax='proto3',
  serialized_options=_b('\252\002\024CoralReef.Api.Serial'),
  serialized_pb=_b('\n\x13serial/serial.proto\x12\x14\x63oralreef.api.serial\"\xcd\x07\n\x0bSerialFrame\x12\x1c\n\x14\x66orward_backward_num\x18\x01 \x01(\x05\x12\x16\n\x0eleft_right_num\x18\x02 \x01(\x05\x12\x13\n\x0bup_down_num\x18\x03 \x01(\x05\x12\x17\n\x0f\x66ront_light_num\x18\x04 \x01(\x05\x12\x16\n\x0e\x62\x61\x63k_light_num\x18\x05 \x01(\x05\x12\x0f\n\x07ptz_num\x18\x06 \x01(\x05\x12\x11\n\twrist_num\x18\x07 \x01(\x05\x12\x10\n\x08roll_num\x18\x08 \x01(\x05\x12\x14\n\x0claser_toggle\x18\t \x01(\x08\x12\x14\n\x0c\x63lamp_toggle\x18\n \x01(\x08\x12\x12\n\narm_toggle\x18\x0b \x01(\x08\x12\x14\n\x0csonar_toggle\x18\x0c \x01(\x08\x12\x15\n\rcamara_toggle\x18\r \x01(\x08\x12\x16\n\x0eheading_toggle\x18\x0e \x01(\x08\x12\x14\n\x0c\x64\x65pth_toggle\x18\x0f \x01(\x08\x12\x15\n\rrescue_toggle\x18\x10 \x01(\x08\x12\x18\n\x10side_push_toggle\x18\x11 \x01(\x08\x12\x16\n\x0eposture_toggle\x18\x12 \x01(\x08\x12\x15\n\rmodule_toggle\x18\x13 \x01(\x08\x12\x18\n\x10\x61uxiliary_toggle\x18\x14 \x01(\x08\x12\x14\n\x0ctrack_toggle\x18\x15 \x01(\x08\x12\x18\n\x10tilt_roll_toggle\x18\x16 \x01(\x08\x12<\n\x0b\x63lamp_state\x18\x17 \x01(\x0e\x32\'.coralreef.api.serial.SerialTenaryState\x12\x42\n\x11\x63\x61mara_zoom_state\x18\x18 \x01(\x0e\x32\'.coralreef.api.serial.SerialTenaryState\x12\x45\n\x14machine_rotate_state\x18\x19 \x01(\x0e\x32\'.coralreef.api.serial.SerialTenaryState\x12\x44\n\x13piercing_post_state\x18\x1a \x01(\x0e\x32\'.coralreef.api.serial.SerialTenaryState\x12>\n\rtrigger_state\x18\x1b \x01(\x0e\x32\'.coralreef.api.serial.SerialTenaryState\x12<\n\x0b\x63\x61\x62le_state\x18\x1c \x01(\x0e\x32\'.coralreef.api.serial.SerialTenaryState\x12:\n\tarm_state\x18\x1d \x01(\x0e\x32\'.coralreef.api.serial.SerialTenaryState*4\n\x11SerialTenaryState\x12\x08\n\x04STOP\x10\x00\x12\x08\n\x04HOLD\x10\x01\x12\x0b\n\x07RELEASE\x10\x02\x42\x17\xaa\x02\x14\x43oralReef.Api.Serialb\x06proto3')
)

_SERIALTENARYSTATE = _descriptor.EnumDescriptor(
  name='SerialTenaryState',
  full_name='coralreef.api.serial.SerialTenaryState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOLD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RELEASE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1021,
  serialized_end=1073,
)
_sym_db.RegisterEnumDescriptor(_SERIALTENARYSTATE)

SerialTenaryState = enum_type_wrapper.EnumTypeWrapper(_SERIALTENARYSTATE)
STOP = 0
HOLD = 1
RELEASE = 2



_SERIALFRAME = _descriptor.Descriptor(
  name='SerialFrame',
  full_name='coralreef.api.serial.SerialFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='forward_backward_num', full_name='coralreef.api.serial.SerialFrame.forward_backward_num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='left_right_num', full_name='coralreef.api.serial.SerialFrame.left_right_num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='up_down_num', full_name='coralreef.api.serial.SerialFrame.up_down_num', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='front_light_num', full_name='coralreef.api.serial.SerialFrame.front_light_num', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='back_light_num', full_name='coralreef.api.serial.SerialFrame.back_light_num', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ptz_num', full_name='coralreef.api.serial.SerialFrame.ptz_num', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wrist_num', full_name='coralreef.api.serial.SerialFrame.wrist_num', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roll_num', full_name='coralreef.api.serial.SerialFrame.roll_num', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='laser_toggle', full_name='coralreef.api.serial.SerialFrame.laser_toggle', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clamp_toggle', full_name='coralreef.api.serial.SerialFrame.clamp_toggle', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arm_toggle', full_name='coralreef.api.serial.SerialFrame.arm_toggle', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sonar_toggle', full_name='coralreef.api.serial.SerialFrame.sonar_toggle', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camara_toggle', full_name='coralreef.api.serial.SerialFrame.camara_toggle', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading_toggle', full_name='coralreef.api.serial.SerialFrame.heading_toggle', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth_toggle', full_name='coralreef.api.serial.SerialFrame.depth_toggle', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rescue_toggle', full_name='coralreef.api.serial.SerialFrame.rescue_toggle', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='side_push_toggle', full_name='coralreef.api.serial.SerialFrame.side_push_toggle', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='posture_toggle', full_name='coralreef.api.serial.SerialFrame.posture_toggle', index=17,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='module_toggle', full_name='coralreef.api.serial.SerialFrame.module_toggle', index=18,
      number=19, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auxiliary_toggle', full_name='coralreef.api.serial.SerialFrame.auxiliary_toggle', index=19,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='track_toggle', full_name='coralreef.api.serial.SerialFrame.track_toggle', index=20,
      number=21, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tilt_roll_toggle', full_name='coralreef.api.serial.SerialFrame.tilt_roll_toggle', index=21,
      number=22, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clamp_state', full_name='coralreef.api.serial.SerialFrame.clamp_state', index=22,
      number=23, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camara_zoom_state', full_name='coralreef.api.serial.SerialFrame.camara_zoom_state', index=23,
      number=24, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='machine_rotate_state', full_name='coralreef.api.serial.SerialFrame.machine_rotate_state', index=24,
      number=25, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='piercing_post_state', full_name='coralreef.api.serial.SerialFrame.piercing_post_state', index=25,
      number=26, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trigger_state', full_name='coralreef.api.serial.SerialFrame.trigger_state', index=26,
      number=27, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cable_state', full_name='coralreef.api.serial.SerialFrame.cable_state', index=27,
      number=28, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arm_state', full_name='coralreef.api.serial.SerialFrame.arm_state', index=28,
      number=29, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=1019,
)

_SERIALFRAME.fields_by_name['clamp_state'].enum_type = _SERIALTENARYSTATE
_SERIALFRAME.fields_by_name['camara_zoom_state'].enum_type = _SERIALTENARYSTATE
_SERIALFRAME.fields_by_name['machine_rotate_state'].enum_type = _SERIALTENARYSTATE
_SERIALFRAME.fields_by_name['piercing_post_state'].enum_type = _SERIALTENARYSTATE
_SERIALFRAME.fields_by_name['trigger_state'].enum_type = _SERIALTENARYSTATE
_SERIALFRAME.fields_by_name['cable_state'].enum_type = _SERIALTENARYSTATE
_SERIALFRAME.fields_by_name['arm_state'].enum_type = _SERIALTENARYSTATE
DESCRIPTOR.message_types_by_name['SerialFrame'] = _SERIALFRAME
DESCRIPTOR.enum_types_by_name['SerialTenaryState'] = _SERIALTENARYSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SerialFrame = _reflection.GeneratedProtocolMessageType('SerialFrame', (_message.Message,), dict(
  DESCRIPTOR = _SERIALFRAME,
  __module__ = 'serial.serial_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.serial.SerialFrame)
  ))
_sym_db.RegisterMessage(SerialFrame)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
