# Target: Python
# Generated by bubbler
# DO NOT EDIT

import struct
from enum import Enum
from typing import List


# ====================== RovExdataLeakageData ======================

# Struct: RovExdataLeakageData [6] {1 fields}
class RovExdataLeakageData:
    def __init__(self):
        # [0:6) NormalField: bool<48> leakage[6]
        self._leakage: List[bool] = [False for i in range(48)]

    @staticmethod
    def size() -> int:
        return 6

    # RawGetter: leakage
    @property
    def leakage(self) -> List[bool]:
        return self._leakage

    # RawSetter: leakage
    @leakage.setter
    def leakage(self, value: List[bool]) -> None:
        self._leakage = value

    # Encoder: RovExdataLeakageData
    def encode(self) -> bytearray:
        data = bytearray(6)
        # [0:6) NormalField: bool<48> leakage[6]
        data[0] = (((((self._leakage[0] >> 0) & 1) >> 0) << 0) & 1)
        data[0] |= (((((self._leakage[1] >> 0) & 1) >> 0) << 1) & 2)
        data[0] |= (((((self._leakage[2] >> 0) & 1) >> 0) << 2) & 4)
        data[0] |= (((((self._leakage[3] >> 0) & 1) >> 0) << 3) & 8)
        data[0] |= (((((self._leakage[4] >> 0) & 1) >> 0) << 4) & 16)
        data[0] |= (((((self._leakage[5] >> 0) & 1) >> 0) << 5) & 32)
        data[0] |= (((((self._leakage[6] >> 0) & 1) >> 0) << 6) & 64)
        data[0] |= (((((self._leakage[7] >> 0) & 1) >> 0) << 7) & 128)
        data[1] = (((((self._leakage[8] >> 0) & 1) >> 0) << 0) & 1)
        data[1] |= (((((self._leakage[9] >> 0) & 1) >> 0) << 1) & 2)
        data[1] |= (((((self._leakage[10] >> 0) & 1) >> 0) << 2) & 4)
        data[1] |= (((((self._leakage[11] >> 0) & 1) >> 0) << 3) & 8)
        data[1] |= (((((self._leakage[12] >> 0) & 1) >> 0) << 4) & 16)
        data[1] |= (((((self._leakage[13] >> 0) & 1) >> 0) << 5) & 32)
        data[1] |= (((((self._leakage[14] >> 0) & 1) >> 0) << 6) & 64)
        data[1] |= (((((self._leakage[15] >> 0) & 1) >> 0) << 7) & 128)
        data[2] = (((((self._leakage[16] >> 0) & 1) >> 0) << 0) & 1)
        data[2] |= (((((self._leakage[17] >> 0) & 1) >> 0) << 1) & 2)
        data[2] |= (((((self._leakage[18] >> 0) & 1) >> 0) << 2) & 4)
        data[2] |= (((((self._leakage[19] >> 0) & 1) >> 0) << 3) & 8)
        data[2] |= (((((self._leakage[20] >> 0) & 1) >> 0) << 4) & 16)
        data[2] |= (((((self._leakage[21] >> 0) & 1) >> 0) << 5) & 32)
        data[2] |= (((((self._leakage[22] >> 0) & 1) >> 0) << 6) & 64)
        data[2] |= (((((self._leakage[23] >> 0) & 1) >> 0) << 7) & 128)
        data[3] = (((((self._leakage[24] >> 0) & 1) >> 0) << 0) & 1)
        data[3] |= (((((self._leakage[25] >> 0) & 1) >> 0) << 1) & 2)
        data[3] |= (((((self._leakage[26] >> 0) & 1) >> 0) << 2) & 4)
        data[3] |= (((((self._leakage[27] >> 0) & 1) >> 0) << 3) & 8)
        data[3] |= (((((self._leakage[28] >> 0) & 1) >> 0) << 4) & 16)
        data[3] |= (((((self._leakage[29] >> 0) & 1) >> 0) << 5) & 32)
        data[3] |= (((((self._leakage[30] >> 0) & 1) >> 0) << 6) & 64)
        data[3] |= (((((self._leakage[31] >> 0) & 1) >> 0) << 7) & 128)
        data[4] = (((((self._leakage[32] >> 0) & 1) >> 0) << 0) & 1)
        data[4] |= (((((self._leakage[33] >> 0) & 1) >> 0) << 1) & 2)
        data[4] |= (((((self._leakage[34] >> 0) & 1) >> 0) << 2) & 4)
        data[4] |= (((((self._leakage[35] >> 0) & 1) >> 0) << 3) & 8)
        data[4] |= (((((self._leakage[36] >> 0) & 1) >> 0) << 4) & 16)
        data[4] |= (((((self._leakage[37] >> 0) & 1) >> 0) << 5) & 32)
        data[4] |= (((((self._leakage[38] >> 0) & 1) >> 0) << 6) & 64)
        data[4] |= (((((self._leakage[39] >> 0) & 1) >> 0) << 7) & 128)
        data[5] = (((((self._leakage[40] >> 0) & 1) >> 0) << 0) & 1)
        data[5] |= (((((self._leakage[41] >> 0) & 1) >> 0) << 1) & 2)
        data[5] |= (((((self._leakage[42] >> 0) & 1) >> 0) << 2) & 4)
        data[5] |= (((((self._leakage[43] >> 0) & 1) >> 0) << 3) & 8)
        data[5] |= (((((self._leakage[44] >> 0) & 1) >> 0) << 4) & 16)
        data[5] |= (((((self._leakage[45] >> 0) & 1) >> 0) << 5) & 32)
        data[5] |= (((((self._leakage[46] >> 0) & 1) >> 0) << 6) & 64)
        data[5] |= (((((self._leakage[47] >> 0) & 1) >> 0) << 7) & 128)
        return data

    # Decoder: RovExdataLeakageData
    def decode(self, data: bytearray) -> bool:
        # [0:6) NormalField: bool<48> leakage[6]
        self._leakage[0] = (((data[0] & 1) >> 0) << 0)
        self._leakage[1] = (((data[0] & 2) >> 1) << 0)
        self._leakage[2] = (((data[0] & 4) >> 2) << 0)
        self._leakage[3] = (((data[0] & 8) >> 3) << 0)
        self._leakage[4] = (((data[0] & 16) >> 4) << 0)
        self._leakage[5] = (((data[0] & 32) >> 5) << 0)
        self._leakage[6] = (((data[0] & 64) >> 6) << 0)
        self._leakage[7] = (((data[0] & 128) >> 7) << 0)
        self._leakage[8] = (((data[1] & 1) >> 0) << 0)
        self._leakage[9] = (((data[1] & 2) >> 1) << 0)
        self._leakage[10] = (((data[1] & 4) >> 2) << 0)
        self._leakage[11] = (((data[1] & 8) >> 3) << 0)
        self._leakage[12] = (((data[1] & 16) >> 4) << 0)
        self._leakage[13] = (((data[1] & 32) >> 5) << 0)
        self._leakage[14] = (((data[1] & 64) >> 6) << 0)
        self._leakage[15] = (((data[1] & 128) >> 7) << 0)
        self._leakage[16] = (((data[2] & 1) >> 0) << 0)
        self._leakage[17] = (((data[2] & 2) >> 1) << 0)
        self._leakage[18] = (((data[2] & 4) >> 2) << 0)
        self._leakage[19] = (((data[2] & 8) >> 3) << 0)
        self._leakage[20] = (((data[2] & 16) >> 4) << 0)
        self._leakage[21] = (((data[2] & 32) >> 5) << 0)
        self._leakage[22] = (((data[2] & 64) >> 6) << 0)
        self._leakage[23] = (((data[2] & 128) >> 7) << 0)
        self._leakage[24] = (((data[3] & 1) >> 0) << 0)
        self._leakage[25] = (((data[3] & 2) >> 1) << 0)
        self._leakage[26] = (((data[3] & 4) >> 2) << 0)
        self._leakage[27] = (((data[3] & 8) >> 3) << 0)
        self._leakage[28] = (((data[3] & 16) >> 4) << 0)
        self._leakage[29] = (((data[3] & 32) >> 5) << 0)
        self._leakage[30] = (((data[3] & 64) >> 6) << 0)
        self._leakage[31] = (((data[3] & 128) >> 7) << 0)
        self._leakage[32] = (((data[4] & 1) >> 0) << 0)
        self._leakage[33] = (((data[4] & 2) >> 1) << 0)
        self._leakage[34] = (((data[4] & 4) >> 2) << 0)
        self._leakage[35] = (((data[4] & 8) >> 3) << 0)
        self._leakage[36] = (((data[4] & 16) >> 4) << 0)
        self._leakage[37] = (((data[4] & 32) >> 5) << 0)
        self._leakage[38] = (((data[4] & 64) >> 6) << 0)
        self._leakage[39] = (((data[4] & 128) >> 7) << 0)
        self._leakage[40] = (((data[5] & 1) >> 0) << 0)
        self._leakage[41] = (((data[5] & 2) >> 1) << 0)
        self._leakage[42] = (((data[5] & 4) >> 2) << 0)
        self._leakage[43] = (((data[5] & 8) >> 3) << 0)
        self._leakage[44] = (((data[5] & 16) >> 4) << 0)
        self._leakage[45] = (((data[5] & 32) >> 5) << 0)
        self._leakage[46] = (((data[5] & 64) >> 6) << 0)
        self._leakage[47] = (((data[5] & 128) >> 7) << 0)
        return True

# ==================== End RovExdataLeakageData ====================

# ====================== RovExdataKeepAliveStatus ======================

# Enum: RovExdataKeepAliveStatus [2] {2 values}
class RovExdataKeepAliveStatus(Enum):
    HEALTHY = 0
    WATCHDOG_TIMEOUT = 1

# ==================== End RovExdataKeepAliveStatus ====================

# ====================== RovExdataKeepAliveData ======================

# Struct: RovExdataKeepAliveData [6] {2 fields}
class RovExdataKeepAliveData:
    def __init__(self):
        # [0:4) NormalField: uint32 timestamp[4]
        self._timestamp: int = 0
        # [4:6) NormalField: RovExdataKeepAliveStatus status[2]
        self._status: RovExdataKeepAliveStatus = None

    @staticmethod
    def size() -> int:
        return 6

    # RawGetter: timestamp
    @property
    def timestamp(self) -> int:
        return self._timestamp

    # RawSetter: timestamp
    @timestamp.setter
    def timestamp(self, value: int) -> None:
        self._timestamp = value

    # RawGetter: status
    @property
    def status(self) -> RovExdataKeepAliveStatus:
        return self._status

    # RawSetter: status
    @status.setter
    def status(self, value: RovExdataKeepAliveStatus) -> None:
        self._status = value

    # Encoder: RovExdataKeepAliveData
    def encode(self) -> bytearray:
        data = bytearray(6)
        # [0:4) NormalField: uint32 timestamp[4]
        data[0] = (((((self._timestamp >> 24) & 255) >> 0) << 0) & 255)
        data[1] = (((((self._timestamp >> 16) & 255) >> 0) << 0) & 255)
        data[2] = (((((self._timestamp >> 8) & 255) >> 0) << 0) & 255)
        data[3] = (((((self._timestamp >> 0) & 255) >> 0) << 0) & 255)
        # [4:6) NormalField: RovExdataKeepAliveStatus status[2]
        temp_field_at_pos_32 = self._status.value
        data[4] = (((((temp_field_at_pos_32 >> 8) & 255) >> 0) << 0) & 255)
        data[5] = (((((temp_field_at_pos_32 >> 0) & 255) >> 0) << 0) & 255)
        return data

    # Decoder: RovExdataKeepAliveData
    def decode(self, data: bytearray) -> bool:
        # [0:4) NormalField: uint32 timestamp[4]
        self._timestamp = (((data[0] & 255) >> 0) << 24)
        self._timestamp |= (((data[1] & 255) >> 0) << 16)
        self._timestamp |= (((data[2] & 255) >> 0) << 8)
        self._timestamp |= (((data[3] & 255) >> 0) << 0)
        # [4:6) NormalField: RovExdataKeepAliveStatus status[2]
        temp_field_at_pos_32 = (((data[4] & 255) >> 0) << 8)
        temp_field_at_pos_32 |= (((data[5] & 255) >> 0) << 0)
        self._status = RovExdataKeepAliveStatus(temp_field_at_pos_32)
        return True

# ==================== End RovExdataKeepAliveData ====================

