# Target: Python
# Generated by bubbler
# DO NOT EDIT

import struct
from enum import Enum
from typing import List


# ====================== RovCamaraType ======================

# Enum: RovCamaraType [1] {3 values}
class RovCamaraType(Enum):
    NO_CAM = 0
    FRONT_CAM = 1
    BACK_CAM = 2

# ==================== End RovCamaraType ====================

# ====================== RovHostCamaraData ======================

# Struct: RovHostCamaraData [6] {1 fields}
class RovHostCamaraData:
    def __init__(self):
        # [0:6) NormalField: RovCamaraType<6> camara_type[6]
        self._camara_type: List[RovCamaraType] = [None for i in range(6)]

    @staticmethod
    def size() -> int:
        return 6

    # RawGetter: camara_type
    @property
    def camara_type(self) -> List[RovCamaraType]:
        return self._camara_type

    # RawSetter: camara_type
    @camara_type.setter
    def camara_type(self, value: List[RovCamaraType]) -> None:
        self._camara_type = value

    # Encoder: RovHostCamaraData
    def encode(self) -> bytearray:
        data = bytearray(6)
        # [0:6) NormalField: RovCamaraType<6> camara_type[6]
        temp_field_at_pos_0 = self._camara_type[0].value
        data[0] = (((((temp_field_at_pos_0 >> 0) & 255) >> 0) << 0) & 255)
        temp_field_at_pos_0 = self._camara_type[1].value
        data[1] = (((((temp_field_at_pos_0 >> 0) & 255) >> 0) << 0) & 255)
        temp_field_at_pos_0 = self._camara_type[2].value
        data[2] = (((((temp_field_at_pos_0 >> 0) & 255) >> 0) << 0) & 255)
        temp_field_at_pos_0 = self._camara_type[3].value
        data[3] = (((((temp_field_at_pos_0 >> 0) & 255) >> 0) << 0) & 255)
        temp_field_at_pos_0 = self._camara_type[4].value
        data[4] = (((((temp_field_at_pos_0 >> 0) & 255) >> 0) << 0) & 255)
        temp_field_at_pos_0 = self._camara_type[5].value
        data[5] = (((((temp_field_at_pos_0 >> 0) & 255) >> 0) << 0) & 255)
        return data

    # Decoder: RovHostCamaraData
    def decode(self, data: bytearray) -> bool:
        # [0:6) NormalField: RovCamaraType<6> camara_type[6]
        temp_field_at_pos_0 = (((data[0] & 255) >> 0) << 0)
        self._camara_type[0] = RovCamaraType(temp_field_at_pos_0)
        temp_field_at_pos_0 = (((data[1] & 255) >> 0) << 0)
        self._camara_type[1] = RovCamaraType(temp_field_at_pos_0)
        temp_field_at_pos_0 = (((data[2] & 255) >> 0) << 0)
        self._camara_type[2] = RovCamaraType(temp_field_at_pos_0)
        temp_field_at_pos_0 = (((data[3] & 255) >> 0) << 0)
        self._camara_type[3] = RovCamaraType(temp_field_at_pos_0)
        temp_field_at_pos_0 = (((data[4] & 255) >> 0) << 0)
        self._camara_type[4] = RovCamaraType(temp_field_at_pos_0)
        temp_field_at_pos_0 = (((data[5] & 255) >> 0) << 0)
        self._camara_type[5] = RovCamaraType(temp_field_at_pos_0)
        return True

# ==================== End RovHostCamaraData ====================

