# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: host/host.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
import rovlink_proto.device_pb2 as device__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='host/host.proto',
  package='coralreef.api.host',
  syntax='proto3',
  serialized_options=_b('\252\002\022CoralReef.Api.Host'),
  serialized_pb=_b('\n\x0fhost/host.proto\x12\x12\x63oralreef.api.host\x1a\x19google/protobuf/any.proto\x1a\x0c\x64\x65vice.proto\"\x7f\n\x03Log\x12\x0e\n\x06member\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\x12\x0c\n\x04line\x18\x03 \x01(\x05\x12+\n\x05level\x18\x04 \x01(\x0e\x32\x1c.coralreef.api.host.LogLevel\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x06 \x01(\t\"\x91\x01\n\x10\x44\x65viceStateFrame\x12)\n\x06\x64\x65vice\x18\x01 \x01(\x0e\x32\x19.coralreef.api.DeviceType\x12.\n\x05state\x18\x02 \x01(\x0e\x32\x1f.coralreef.api.host.DeviceState\x12\"\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any*W\n\x08LogLevel\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05TRACE\x10\x01\x12\t\n\x05\x44\x45\x42UG\x10\x02\x12\x08\n\x04INFO\x10\x03\x12\x0b\n\x07WARNING\x10\x04\x12\t\n\x05\x45RROR\x10\x05\x12\t\n\x05\x46\x41TAL\x10\x06*Q\n\x0b\x44\x65viceState\x12\x0b\n\x07OFFLINE\x10\x00\x12\n\n\x06ONLINE\x10\x01\x12\x14\n\x10OFFLINE_EXTERNAL\x10\x02\x12\x13\n\x0fONLINE_EXTERNAL\x10\x03\x42\x15\xaa\x02\x12\x43oralReef.Api.Hostb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,device__pb2.DESCRIPTOR,])

_LOGLEVEL = _descriptor.EnumDescriptor(
  name='LogLevel',
  full_name='coralreef.api.host.LogLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRACE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEBUG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INFO', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FATAL', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=357,
  serialized_end=444,
)
_sym_db.RegisterEnumDescriptor(_LOGLEVEL)

LogLevel = enum_type_wrapper.EnumTypeWrapper(_LOGLEVEL)
_DEVICESTATE = _descriptor.EnumDescriptor(
  name='DeviceState',
  full_name='coralreef.api.host.DeviceState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFFLINE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONLINE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OFFLINE_EXTERNAL', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONLINE_EXTERNAL', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=446,
  serialized_end=527,
)
_sym_db.RegisterEnumDescriptor(_DEVICESTATE)

DeviceState = enum_type_wrapper.EnumTypeWrapper(_DEVICESTATE)
NONE = 0
TRACE = 1
DEBUG = 2
INFO = 3
WARNING = 4
ERROR = 5
FATAL = 6
OFFLINE = 0
ONLINE = 1
OFFLINE_EXTERNAL = 2
ONLINE_EXTERNAL = 3



_LOG = _descriptor.Descriptor(
  name='Log',
  full_name='coralreef.api.host.Log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='member', full_name='coralreef.api.host.Log.member', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file', full_name='coralreef.api.host.Log.file', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='line', full_name='coralreef.api.host.Log.line', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='coralreef.api.host.Log.level', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='coralreef.api.host.Log.message', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detail', full_name='coralreef.api.host.Log.detail', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=207,
)


_DEVICESTATEFRAME = _descriptor.Descriptor(
  name='DeviceStateFrame',
  full_name='coralreef.api.host.DeviceStateFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device', full_name='coralreef.api.host.DeviceStateFrame.device', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='coralreef.api.host.DeviceStateFrame.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='coralreef.api.host.DeviceStateFrame.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=355,
)

_LOG.fields_by_name['level'].enum_type = _LOGLEVEL
_DEVICESTATEFRAME.fields_by_name['device'].enum_type = device__pb2._DEVICETYPE
_DEVICESTATEFRAME.fields_by_name['state'].enum_type = _DEVICESTATE
_DEVICESTATEFRAME.fields_by_name['data'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['Log'] = _LOG
DESCRIPTOR.message_types_by_name['DeviceStateFrame'] = _DEVICESTATEFRAME
DESCRIPTOR.enum_types_by_name['LogLevel'] = _LOGLEVEL
DESCRIPTOR.enum_types_by_name['DeviceState'] = _DEVICESTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Log = _reflection.GeneratedProtocolMessageType('Log', (_message.Message,), dict(
  DESCRIPTOR = _LOG,
  __module__ = 'host.host_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.host.Log)
  ))
_sym_db.RegisterMessage(Log)

DeviceStateFrame = _reflection.GeneratedProtocolMessageType('DeviceStateFrame', (_message.Message,), dict(
  DESCRIPTOR = _DEVICESTATEFRAME,
  __module__ = 'host.host_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.host.DeviceStateFrame)
  ))
_sym_db.RegisterMessage(DeviceStateFrame)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
