# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: host/video.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
import rovlink_proto.device_pb2 as device__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='host/video.proto',
  package='coralreef.api.host',
  syntax='proto3',
  serialized_options=_b('\252\002\022CoralReef.Api.Host'),
  serialized_pb=_b('\n\x10host/video.proto\x12\x12\x63oralreef.api.host\x1a\x19google/protobuf/any.proto\x1a\x0c\x64\x65vice.proto\"\xd6\x01\n\nVideoFrame\x12\x0e\n\x06signal\x18\x01 \x01(\x08\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0e\n\x06stride\x18\x04 \x01(\x05\x12\x13\n\x0b\x64\x61ta_length\x18\x05 \x01(\x05\x12\x31\n\npix_format\x18\x06 \x01(\x0e\x32\x1d.coralreef.api.host.PixFormat\x12\r\n\x05scan0\x18\x07 \x01(\x0c\x12\x12\n\ncompressed\x18\x08 \x01(\x08\x12\x1e\n\x16\x63ompressed_data_length\x18\t \x01(\x05\"\x96\x01\n\x11VideoControlFrame\x12)\n\x06\x64\x65vice\x18\x01 \x01(\x0e\x32\x19.coralreef.api.DeviceType\x12\x32\n\x04type\x18\x02 \x01(\x0e\x32$.coralreef.api.host.VideoControlType\x12\"\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any*9\n\tPixFormat\x12\t\n\x05RGB24\x10\x00\x12\t\n\x05\x42GR24\x10\x01\x12\n\n\x06\x42GRA32\x10\x02\x12\n\n\x06\x42GR032\x10\x03*[\n\x10VideoControlType\x12\r\n\tNOCONTROL\x10\x00\x12\x0f\n\x0bUNSUBSCRIBE\x10\x01\x12\x13\n\x0fSUBSCRIBE_MJPEG\x10\x02\x12\x12\n\x0eSUBSCRIBE_H264\x10\x03\x42\x15\xaa\x02\x12\x43oralReef.Api.Hostb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,device__pb2.DESCRIPTOR,])

_PIXFORMAT = _descriptor.EnumDescriptor(
  name='PixFormat',
  full_name='coralreef.api.host.PixFormat',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RGB24', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BGR24', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BGRA32', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BGR032', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=451,
  serialized_end=508,
)
_sym_db.RegisterEnumDescriptor(_PIXFORMAT)

PixFormat = enum_type_wrapper.EnumTypeWrapper(_PIXFORMAT)
_VIDEOCONTROLTYPE = _descriptor.EnumDescriptor(
  name='VideoControlType',
  full_name='coralreef.api.host.VideoControlType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOCONTROL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNSUBSCRIBE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUBSCRIBE_MJPEG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUBSCRIBE_H264', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=510,
  serialized_end=601,
)
_sym_db.RegisterEnumDescriptor(_VIDEOCONTROLTYPE)

VideoControlType = enum_type_wrapper.EnumTypeWrapper(_VIDEOCONTROLTYPE)
RGB24 = 0
BGR24 = 1
BGRA32 = 2
BGR032 = 3
NOCONTROL = 0
UNSUBSCRIBE = 1
SUBSCRIBE_MJPEG = 2
SUBSCRIBE_H264 = 3



_VIDEOFRAME = _descriptor.Descriptor(
  name='VideoFrame',
  full_name='coralreef.api.host.VideoFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signal', full_name='coralreef.api.host.VideoFrame.signal', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='coralreef.api.host.VideoFrame.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='coralreef.api.host.VideoFrame.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stride', full_name='coralreef.api.host.VideoFrame.stride', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_length', full_name='coralreef.api.host.VideoFrame.data_length', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pix_format', full_name='coralreef.api.host.VideoFrame.pix_format', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scan0', full_name='coralreef.api.host.VideoFrame.scan0', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compressed', full_name='coralreef.api.host.VideoFrame.compressed', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compressed_data_length', full_name='coralreef.api.host.VideoFrame.compressed_data_length', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=296,
)


_VIDEOCONTROLFRAME = _descriptor.Descriptor(
  name='VideoControlFrame',
  full_name='coralreef.api.host.VideoControlFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device', full_name='coralreef.api.host.VideoControlFrame.device', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='coralreef.api.host.VideoControlFrame.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='coralreef.api.host.VideoControlFrame.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=449,
)

_VIDEOFRAME.fields_by_name['pix_format'].enum_type = _PIXFORMAT
_VIDEOCONTROLFRAME.fields_by_name['device'].enum_type = device__pb2._DEVICETYPE
_VIDEOCONTROLFRAME.fields_by_name['type'].enum_type = _VIDEOCONTROLTYPE
_VIDEOCONTROLFRAME.fields_by_name['data'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['VideoFrame'] = _VIDEOFRAME
DESCRIPTOR.message_types_by_name['VideoControlFrame'] = _VIDEOCONTROLFRAME
DESCRIPTOR.enum_types_by_name['PixFormat'] = _PIXFORMAT
DESCRIPTOR.enum_types_by_name['VideoControlType'] = _VIDEOCONTROLTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoFrame = _reflection.GeneratedProtocolMessageType('VideoFrame', (_message.Message,), dict(
  DESCRIPTOR = _VIDEOFRAME,
  __module__ = 'host.video_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.host.VideoFrame)
  ))
_sym_db.RegisterMessage(VideoFrame)

VideoControlFrame = _reflection.GeneratedProtocolMessageType('VideoControlFrame', (_message.Message,), dict(
  DESCRIPTOR = _VIDEOCONTROLFRAME,
  __module__ = 'host.video_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.host.VideoControlFrame)
  ))
_sym_db.RegisterMessage(VideoControlFrame)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
