# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='device.proto',
  package='coralreef.api',
  syntax='proto3',
  serialized_options=_b('\252\002\rCoralReef.Api'),
  serialized_pb=_b('\n\x0c\x64\x65vice.proto\x12\rcoralreef.api*\xa0\x01\n\nDeviceType\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04HOST\x10\x11\x12\x0c\n\x08\x45XTERNAL\x10\x12\x12\t\n\x05ROBOT\x10!\x12\n\n\x06SERIAL\x10\"\x12\x0b\n\x07GAMEPAD\x10#\x12\x0b\n\x07\x43HASSIS\x10$\x12\x10\n\x0c\x46RONT_CAMARA\x10\x31\x12\x0f\n\x0b\x42\x41\x43K_CAMARA\x10\x32\x12\x12\n\x0e\x43HASSIS_CAMARA\x10\x33\x12\x08\n\x03\x41NY\x10\xff\x01\x42\x10\xaa\x02\rCoralReef.Apib\x06proto3')
)

_DEVICETYPE = _descriptor.EnumDescriptor(
  name='DeviceType',
  full_name='coralreef.api.DeviceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOST', index=1, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXTERNAL', index=2, number=18,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROBOT', index=3, number=33,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERIAL', index=4, number=34,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAMEPAD', index=5, number=35,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHASSIS', index=6, number=36,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRONT_CAMARA', index=7, number=49,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BACK_CAMARA', index=8, number=50,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHASSIS_CAMARA', index=9, number=51,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANY', index=10, number=255,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=32,
  serialized_end=192,
)
_sym_db.RegisterEnumDescriptor(_DEVICETYPE)

DeviceType = enum_type_wrapper.EnumTypeWrapper(_DEVICETYPE)
NONE = 0
HOST = 17
EXTERNAL = 18
ROBOT = 33
SERIAL = 34
GAMEPAD = 35
CHASSIS = 36
FRONT_CAMARA = 49
BACK_CAMARA = 50
CHASSIS_CAMARA = 51
ANY = 255


DESCRIPTOR.enum_types_by_name['DeviceType'] = _DEVICETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
