# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: package.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import rovlink_proto.device_pb2 as device__pb2
from rovlink_proto.host import host_pb2 as host_dot_host__pb2
from rovlink_proto.host import video_pb2 as host_dot_video__pb2
from rovlink_proto.serial import serial_pb2 as serial_dot_serial__pb2
from rovlink_proto.rovlink import rovlink_pb2 as rovlink_dot_rovlink__pb2
from rovlink_proto.chassis import chassis_pb2 as chassis_dot_chassis__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='package.proto',
  package='coralreef.api',
  syntax='proto3',
  serialized_options=_b('\252\002\rCoralReef.Api'),
  serialized_pb=_b('\n\rpackage.proto\x12\rcoralreef.api\x1a\x0c\x64\x65vice.proto\x1a\x0fhost/host.proto\x1a\x10host/video.proto\x1a\x13serial/serial.proto\x1a\x15rovlink/rovlink.proto\x1a\x15\x63hassis/chassis.proto\"\x98\x05\n\x07Package\x12\n\n\x02id\x18\x01 \x01(\r\x12)\n\x06source\x18\x02 \x01(\x0e\x32\x19.coralreef.api.DeviceType\x12)\n\x06target\x18\x03 \x01(\x0e\x32\x19.coralreef.api.DeviceType\x12\x14\n\nraw_string\x18\x0b \x01(\tH\x00\x12\x13\n\traw_bytes\x18\x0c \x01(\x0cH\x00\x12&\n\x03log\x18\x15 \x01(\x0b\x32\x17.coralreef.api.host.LogH\x00\x12\x42\n\x12\x64\x65vice_state_frame\x18\x16 \x01(\x0b\x32$.coralreef.api.host.DeviceStateFrameH\x00\x12\x35\n\x0bvideo_frame\x18\x17 \x01(\x0b\x32\x1e.coralreef.api.host.VideoFrameH\x00\x12\x44\n\x13video_control_frame\x18\x18 \x01(\x0b\x32%.coralreef.api.host.VideoControlFrameH\x00\x12\x39\n\x0cserial_frame\x18\x1f \x01(\x0b\x32!.coralreef.api.serial.SerialFrameH\x00\x12<\n\rrovlink_frame\x18  \x01(\x0b\x32#.coralreef.api.rovlink.RovlinkFrameH\x00\x12K\n\x15\x63hassis_control_frame\x18! \x01(\x0b\x32*.coralreef.api.chassis.ChassisControlFrameH\x00\x12I\n\x14\x63hassis_sensor_frame\x18\" \x01(\x0b\x32).coralreef.api.chassis.ChassisSensorFrameH\x00\x42\x06\n\x04\x64\x61taB\x10\xaa\x02\rCoralReef.Apib\x06proto3')
  ,
  dependencies=[device__pb2.DESCRIPTOR,host_dot_host__pb2.DESCRIPTOR,host_dot_video__pb2.DESCRIPTOR,serial_dot_serial__pb2.DESCRIPTOR,rovlink_dot_rovlink__pb2.DESCRIPTOR,chassis_dot_chassis__pb2.DESCRIPTOR,])




_PACKAGE = _descriptor.Descriptor(
  name='Package',
  full_name='coralreef.api.Package',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='coralreef.api.Package.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='coralreef.api.Package.source', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='coralreef.api.Package.target', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_string', full_name='coralreef.api.Package.raw_string', index=3,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_bytes', full_name='coralreef.api.Package.raw_bytes', index=4,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log', full_name='coralreef.api.Package.log', index=5,
      number=21, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_state_frame', full_name='coralreef.api.Package.device_state_frame', index=6,
      number=22, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_frame', full_name='coralreef.api.Package.video_frame', index=7,
      number=23, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_control_frame', full_name='coralreef.api.Package.video_control_frame', index=8,
      number=24, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serial_frame', full_name='coralreef.api.Package.serial_frame', index=9,
      number=31, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rovlink_frame', full_name='coralreef.api.Package.rovlink_frame', index=10,
      number=32, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chassis_control_frame', full_name='coralreef.api.Package.chassis_control_frame', index=11,
      number=33, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chassis_sensor_frame', full_name='coralreef.api.Package.chassis_sensor_frame', index=12,
      number=34, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='coralreef.api.Package.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=149,
  serialized_end=813,
)

_PACKAGE.fields_by_name['source'].enum_type = device__pb2._DEVICETYPE
_PACKAGE.fields_by_name['target'].enum_type = device__pb2._DEVICETYPE
_PACKAGE.fields_by_name['log'].message_type = host_dot_host__pb2._LOG
_PACKAGE.fields_by_name['device_state_frame'].message_type = host_dot_host__pb2._DEVICESTATEFRAME
_PACKAGE.fields_by_name['video_frame'].message_type = host_dot_video__pb2._VIDEOFRAME
_PACKAGE.fields_by_name['video_control_frame'].message_type = host_dot_video__pb2._VIDEOCONTROLFRAME
_PACKAGE.fields_by_name['serial_frame'].message_type = serial_dot_serial__pb2._SERIALFRAME
_PACKAGE.fields_by_name['rovlink_frame'].message_type = rovlink_dot_rovlink__pb2._ROVLINKFRAME
_PACKAGE.fields_by_name['chassis_control_frame'].message_type = chassis_dot_chassis__pb2._CHASSISCONTROLFRAME
_PACKAGE.fields_by_name['chassis_sensor_frame'].message_type = chassis_dot_chassis__pb2._CHASSISSENSORFRAME
_PACKAGE.oneofs_by_name['data'].fields.append(
  _PACKAGE.fields_by_name['raw_string'])
_PACKAGE.fields_by_name['raw_string'].containing_oneof = _PACKAGE.oneofs_by_name['data']
_PACKAGE.oneofs_by_name['data'].fields.append(
  _PACKAGE.fields_by_name['raw_bytes'])
_PACKAGE.fields_by_name['raw_bytes'].containing_oneof = _PACKAGE.oneofs_by_name['data']
_PACKAGE.oneofs_by_name['data'].fields.append(
  _PACKAGE.fields_by_name['log'])
_PACKAGE.fields_by_name['log'].containing_oneof = _PACKAGE.oneofs_by_name['data']
_PACKAGE.oneofs_by_name['data'].fields.append(
  _PACKAGE.fields_by_name['device_state_frame'])
_PACKAGE.fields_by_name['device_state_frame'].containing_oneof = _PACKAGE.oneofs_by_name['data']
_PACKAGE.oneofs_by_name['data'].fields.append(
  _PACKAGE.fields_by_name['video_frame'])
_PACKAGE.fields_by_name['video_frame'].containing_oneof = _PACKAGE.oneofs_by_name['data']
_PACKAGE.oneofs_by_name['data'].fields.append(
  _PACKAGE.fields_by_name['video_control_frame'])
_PACKAGE.fields_by_name['video_control_frame'].containing_oneof = _PACKAGE.oneofs_by_name['data']
_PACKAGE.oneofs_by_name['data'].fields.append(
  _PACKAGE.fields_by_name['serial_frame'])
_PACKAGE.fields_by_name['serial_frame'].containing_oneof = _PACKAGE.oneofs_by_name['data']
_PACKAGE.oneofs_by_name['data'].fields.append(
  _PACKAGE.fields_by_name['rovlink_frame'])
_PACKAGE.fields_by_name['rovlink_frame'].containing_oneof = _PACKAGE.oneofs_by_name['data']
_PACKAGE.oneofs_by_name['data'].fields.append(
  _PACKAGE.fields_by_name['chassis_control_frame'])
_PACKAGE.fields_by_name['chassis_control_frame'].containing_oneof = _PACKAGE.oneofs_by_name['data']
_PACKAGE.oneofs_by_name['data'].fields.append(
  _PACKAGE.fields_by_name['chassis_sensor_frame'])
_PACKAGE.fields_by_name['chassis_sensor_frame'].containing_oneof = _PACKAGE.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['Package'] = _PACKAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Package = _reflection.GeneratedProtocolMessageType('Package', (_message.Message,), dict(
  DESCRIPTOR = _PACKAGE,
  __module__ = 'package_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.Package)
  ))
_sym_db.RegisterMessage(Package)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
