# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rovlink/control.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rovlink/control.proto',
  package='coralreef.api.rovlink',
  syntax='proto3',
  serialized_options=_b('\252\002\025CoralReef.Api.Rovlink'),
  serialized_pb=_b('\n\x15rovlink/control.proto\x12\x15\x63oralreef.api.rovlink\">\n\x18RovControlPropellerAData\x12\n\n\x02\x61\x31\x18\x01 \x01(\r\x12\n\n\x02\x61\x32\x18\x02 \x01(\r\x12\n\n\x02\x61\x33\x18\x03 \x01(\r\">\n\x18RovControlPropellerBData\x12\n\n\x02\x62\x31\x18\x01 \x01(\r\x12\n\n\x02\x62\x32\x18\x02 \x01(\r\x12\n\n\x02\x62\x33\x18\x03 \x01(\r\">\n\x18RovControlPropellerCData\x12\n\n\x02\x63\x31\x18\x01 \x01(\r\x12\n\n\x02\x63\x32\x18\x02 \x01(\r\x12\n\n\x02\x63\x33\x18\x03 \x01(\r\">\n\x18RovControlPropellerDData\x12\n\n\x02\x64\x31\x18\x01 \x01(\r\x12\n\n\x02\x64\x32\x18\x02 \x01(\r\x12\n\n\x02\x64\x33\x18\x03 \x01(\r\":\n\x14RovControlLightAData\x12\n\n\x02l1\x18\x01 \x01(\r\x12\n\n\x02l2\x18\x02 \x01(\r\x12\n\n\x02l3\x18\x03 \x01(\r\":\n\x14RovControlLightBData\x12\n\n\x02l4\x18\x01 \x01(\r\x12\n\n\x02l5\x18\x02 \x01(\r\x12\n\n\x02l6\x18\x03 \x01(\r\":\n\x11RovControlPtzData\x12\x0b\n\x03th1\x18\x01 \x01(\r\x12\x0b\n\x03th2\x18\x02 \x01(\r\x12\x0b\n\x03th3\x18\x03 \x01(\r\"@\n\x14RovControlServoAData\x12\x0c\n\x04pwm1\x18\x01 \x01(\r\x12\x0c\n\x04pwm2\x18\x02 \x01(\r\x12\x0c\n\x04pwm3\x18\x03 \x01(\r\"@\n\x14RovControlServoBData\x12\x0c\n\x04pwm4\x18\x01 \x01(\r\x12\x0c\n\x04pwm5\x18\x02 \x01(\r\x12\x0c\n\x04pwm6\x18\x03 \x01(\r\"@\n\x14RovControlServoCData\x12\x0c\n\x04pwm7\x18\x01 \x01(\r\x12\x0c\n\x04pwm8\x18\x02 \x01(\r\x12\x0c\n\x04pwm9\x18\x03 \x01(\r\"V\n\x15RovControlPostureData\x12\x18\n\x10\x66orward_backward\x18\x01 \x01(\r\x12\x12\n\nleft_right\x18\x02 \x01(\r\x12\x0f\n\x07up_down\x18\x03 \x01(\rB\x18\xaa\x02\x15\x43oralReef.Api.Rovlinkb\x06proto3')
)




_ROVCONTROLPROPELLERADATA = _descriptor.Descriptor(
  name='RovControlPropellerAData',
  full_name='coralreef.api.rovlink.RovControlPropellerAData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a1', full_name='coralreef.api.rovlink.RovControlPropellerAData.a1', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='a2', full_name='coralreef.api.rovlink.RovControlPropellerAData.a2', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='a3', full_name='coralreef.api.rovlink.RovControlPropellerAData.a3', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=110,
)


_ROVCONTROLPROPELLERBDATA = _descriptor.Descriptor(
  name='RovControlPropellerBData',
  full_name='coralreef.api.rovlink.RovControlPropellerBData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='b1', full_name='coralreef.api.rovlink.RovControlPropellerBData.b1', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b2', full_name='coralreef.api.rovlink.RovControlPropellerBData.b2', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b3', full_name='coralreef.api.rovlink.RovControlPropellerBData.b3', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=174,
)


_ROVCONTROLPROPELLERCDATA = _descriptor.Descriptor(
  name='RovControlPropellerCData',
  full_name='coralreef.api.rovlink.RovControlPropellerCData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='c1', full_name='coralreef.api.rovlink.RovControlPropellerCData.c1', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c2', full_name='coralreef.api.rovlink.RovControlPropellerCData.c2', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c3', full_name='coralreef.api.rovlink.RovControlPropellerCData.c3', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=238,
)


_ROVCONTROLPROPELLERDDATA = _descriptor.Descriptor(
  name='RovControlPropellerDData',
  full_name='coralreef.api.rovlink.RovControlPropellerDData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='d1', full_name='coralreef.api.rovlink.RovControlPropellerDData.d1', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='d2', full_name='coralreef.api.rovlink.RovControlPropellerDData.d2', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='d3', full_name='coralreef.api.rovlink.RovControlPropellerDData.d3', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=302,
)


_ROVCONTROLLIGHTADATA = _descriptor.Descriptor(
  name='RovControlLightAData',
  full_name='coralreef.api.rovlink.RovControlLightAData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='l1', full_name='coralreef.api.rovlink.RovControlLightAData.l1', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='l2', full_name='coralreef.api.rovlink.RovControlLightAData.l2', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='l3', full_name='coralreef.api.rovlink.RovControlLightAData.l3', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=362,
)


_ROVCONTROLLIGHTBDATA = _descriptor.Descriptor(
  name='RovControlLightBData',
  full_name='coralreef.api.rovlink.RovControlLightBData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='l4', full_name='coralreef.api.rovlink.RovControlLightBData.l4', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='l5', full_name='coralreef.api.rovlink.RovControlLightBData.l5', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='l6', full_name='coralreef.api.rovlink.RovControlLightBData.l6', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=422,
)


_ROVCONTROLPTZDATA = _descriptor.Descriptor(
  name='RovControlPtzData',
  full_name='coralreef.api.rovlink.RovControlPtzData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='th1', full_name='coralreef.api.rovlink.RovControlPtzData.th1', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='th2', full_name='coralreef.api.rovlink.RovControlPtzData.th2', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='th3', full_name='coralreef.api.rovlink.RovControlPtzData.th3', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=482,
)


_ROVCONTROLSERVOADATA = _descriptor.Descriptor(
  name='RovControlServoAData',
  full_name='coralreef.api.rovlink.RovControlServoAData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pwm1', full_name='coralreef.api.rovlink.RovControlServoAData.pwm1', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pwm2', full_name='coralreef.api.rovlink.RovControlServoAData.pwm2', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pwm3', full_name='coralreef.api.rovlink.RovControlServoAData.pwm3', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=548,
)


_ROVCONTROLSERVOBDATA = _descriptor.Descriptor(
  name='RovControlServoBData',
  full_name='coralreef.api.rovlink.RovControlServoBData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pwm4', full_name='coralreef.api.rovlink.RovControlServoBData.pwm4', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pwm5', full_name='coralreef.api.rovlink.RovControlServoBData.pwm5', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pwm6', full_name='coralreef.api.rovlink.RovControlServoBData.pwm6', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=550,
  serialized_end=614,
)


_ROVCONTROLSERVOCDATA = _descriptor.Descriptor(
  name='RovControlServoCData',
  full_name='coralreef.api.rovlink.RovControlServoCData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pwm7', full_name='coralreef.api.rovlink.RovControlServoCData.pwm7', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pwm8', full_name='coralreef.api.rovlink.RovControlServoCData.pwm8', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pwm9', full_name='coralreef.api.rovlink.RovControlServoCData.pwm9', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=616,
  serialized_end=680,
)


_ROVCONTROLPOSTUREDATA = _descriptor.Descriptor(
  name='RovControlPostureData',
  full_name='coralreef.api.rovlink.RovControlPostureData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='forward_backward', full_name='coralreef.api.rovlink.RovControlPostureData.forward_backward', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='left_right', full_name='coralreef.api.rovlink.RovControlPostureData.left_right', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='up_down', full_name='coralreef.api.rovlink.RovControlPostureData.up_down', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=682,
  serialized_end=768,
)

DESCRIPTOR.message_types_by_name['RovControlPropellerAData'] = _ROVCONTROLPROPELLERADATA
DESCRIPTOR.message_types_by_name['RovControlPropellerBData'] = _ROVCONTROLPROPELLERBDATA
DESCRIPTOR.message_types_by_name['RovControlPropellerCData'] = _ROVCONTROLPROPELLERCDATA
DESCRIPTOR.message_types_by_name['RovControlPropellerDData'] = _ROVCONTROLPROPELLERDDATA
DESCRIPTOR.message_types_by_name['RovControlLightAData'] = _ROVCONTROLLIGHTADATA
DESCRIPTOR.message_types_by_name['RovControlLightBData'] = _ROVCONTROLLIGHTBDATA
DESCRIPTOR.message_types_by_name['RovControlPtzData'] = _ROVCONTROLPTZDATA
DESCRIPTOR.message_types_by_name['RovControlServoAData'] = _ROVCONTROLSERVOADATA
DESCRIPTOR.message_types_by_name['RovControlServoBData'] = _ROVCONTROLSERVOBDATA
DESCRIPTOR.message_types_by_name['RovControlServoCData'] = _ROVCONTROLSERVOCDATA
DESCRIPTOR.message_types_by_name['RovControlPostureData'] = _ROVCONTROLPOSTUREDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RovControlPropellerAData = _reflection.GeneratedProtocolMessageType('RovControlPropellerAData', (_message.Message,), dict(
  DESCRIPTOR = _ROVCONTROLPROPELLERADATA,
  __module__ = 'rovlink.control_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovControlPropellerAData)
  ))
_sym_db.RegisterMessage(RovControlPropellerAData)

RovControlPropellerBData = _reflection.GeneratedProtocolMessageType('RovControlPropellerBData', (_message.Message,), dict(
  DESCRIPTOR = _ROVCONTROLPROPELLERBDATA,
  __module__ = 'rovlink.control_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovControlPropellerBData)
  ))
_sym_db.RegisterMessage(RovControlPropellerBData)

RovControlPropellerCData = _reflection.GeneratedProtocolMessageType('RovControlPropellerCData', (_message.Message,), dict(
  DESCRIPTOR = _ROVCONTROLPROPELLERCDATA,
  __module__ = 'rovlink.control_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovControlPropellerCData)
  ))
_sym_db.RegisterMessage(RovControlPropellerCData)

RovControlPropellerDData = _reflection.GeneratedProtocolMessageType('RovControlPropellerDData', (_message.Message,), dict(
  DESCRIPTOR = _ROVCONTROLPROPELLERDDATA,
  __module__ = 'rovlink.control_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovControlPropellerDData)
  ))
_sym_db.RegisterMessage(RovControlPropellerDData)

RovControlLightAData = _reflection.GeneratedProtocolMessageType('RovControlLightAData', (_message.Message,), dict(
  DESCRIPTOR = _ROVCONTROLLIGHTADATA,
  __module__ = 'rovlink.control_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovControlLightAData)
  ))
_sym_db.RegisterMessage(RovControlLightAData)

RovControlLightBData = _reflection.GeneratedProtocolMessageType('RovControlLightBData', (_message.Message,), dict(
  DESCRIPTOR = _ROVCONTROLLIGHTBDATA,
  __module__ = 'rovlink.control_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovControlLightBData)
  ))
_sym_db.RegisterMessage(RovControlLightBData)

RovControlPtzData = _reflection.GeneratedProtocolMessageType('RovControlPtzData', (_message.Message,), dict(
  DESCRIPTOR = _ROVCONTROLPTZDATA,
  __module__ = 'rovlink.control_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovControlPtzData)
  ))
_sym_db.RegisterMessage(RovControlPtzData)

RovControlServoAData = _reflection.GeneratedProtocolMessageType('RovControlServoAData', (_message.Message,), dict(
  DESCRIPTOR = _ROVCONTROLSERVOADATA,
  __module__ = 'rovlink.control_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovControlServoAData)
  ))
_sym_db.RegisterMessage(RovControlServoAData)

RovControlServoBData = _reflection.GeneratedProtocolMessageType('RovControlServoBData', (_message.Message,), dict(
  DESCRIPTOR = _ROVCONTROLSERVOBDATA,
  __module__ = 'rovlink.control_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovControlServoBData)
  ))
_sym_db.RegisterMessage(RovControlServoBData)

RovControlServoCData = _reflection.GeneratedProtocolMessageType('RovControlServoCData', (_message.Message,), dict(
  DESCRIPTOR = _ROVCONTROLSERVOCDATA,
  __module__ = 'rovlink.control_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovControlServoCData)
  ))
_sym_db.RegisterMessage(RovControlServoCData)

RovControlPostureData = _reflection.GeneratedProtocolMessageType('RovControlPostureData', (_message.Message,), dict(
  DESCRIPTOR = _ROVCONTROLPOSTUREDATA,
  __module__ = 'rovlink.control_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovControlPostureData)
  ))
_sym_db.RegisterMessage(RovControlPostureData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
