# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rovlink/excomponent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rovlink/excomponent.proto',
  package='coralreef.api.rovlink',
  syntax='proto3',
  serialized_options=_b('\252\002\025CoralReef.Api.Rovlink'),
  serialized_pb=_b('\n\x19rovlink/excomponent.proto\x12\x15\x63oralreef.api.rovlink\"s\n\x17RovExcomponentRelayData\x12\r\n\x05lazer\x18\x01 \x01(\x08\x12\r\n\x05\x63lamp\x18\x02 \x01(\x08\x12\x0b\n\x03\x61rm\x18\x03 \x01(\x08\x12\r\n\x05sonar\x18\x04 \x01(\x08\x12\x11\n\tpropeller\x18\x05 \x01(\x08\x12\x0b\n\x03ptz\x18\x06 \x01(\x08\"\x89\x01\n\x18RovExcomponentRescueData\x12\x0f\n\x07stretch\x18\x01 \x01(\r\x12\x12\n\nleft_servo\x18\x02 \x01(\r\x12\x13\n\x0bright_servo\x18\x03 \x01(\r\x12\r\n\x05\x63lamp\x18\x04 \x01(\r\x12\x12\n\nturn_servo\x18\x05 \x01(\r\x12\x10\n\x08solution\x18\x06 \x01(\rB\x18\xaa\x02\x15\x43oralReef.Api.Rovlinkb\x06proto3')
)




_ROVEXCOMPONENTRELAYDATA = _descriptor.Descriptor(
  name='RovExcomponentRelayData',
  full_name='coralreef.api.rovlink.RovExcomponentRelayData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lazer', full_name='coralreef.api.rovlink.RovExcomponentRelayData.lazer', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clamp', full_name='coralreef.api.rovlink.RovExcomponentRelayData.clamp', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arm', full_name='coralreef.api.rovlink.RovExcomponentRelayData.arm', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sonar', full_name='coralreef.api.rovlink.RovExcomponentRelayData.sonar', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='propeller', full_name='coralreef.api.rovlink.RovExcomponentRelayData.propeller', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ptz', full_name='coralreef.api.rovlink.RovExcomponentRelayData.ptz', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=167,
)


_ROVEXCOMPONENTRESCUEDATA = _descriptor.Descriptor(
  name='RovExcomponentRescueData',
  full_name='coralreef.api.rovlink.RovExcomponentRescueData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stretch', full_name='coralreef.api.rovlink.RovExcomponentRescueData.stretch', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='left_servo', full_name='coralreef.api.rovlink.RovExcomponentRescueData.left_servo', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right_servo', full_name='coralreef.api.rovlink.RovExcomponentRescueData.right_servo', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clamp', full_name='coralreef.api.rovlink.RovExcomponentRescueData.clamp', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='turn_servo', full_name='coralreef.api.rovlink.RovExcomponentRescueData.turn_servo', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='solution', full_name='coralreef.api.rovlink.RovExcomponentRescueData.solution', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=307,
)

DESCRIPTOR.message_types_by_name['RovExcomponentRelayData'] = _ROVEXCOMPONENTRELAYDATA
DESCRIPTOR.message_types_by_name['RovExcomponentRescueData'] = _ROVEXCOMPONENTRESCUEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RovExcomponentRelayData = _reflection.GeneratedProtocolMessageType('RovExcomponentRelayData', (_message.Message,), dict(
  DESCRIPTOR = _ROVEXCOMPONENTRELAYDATA,
  __module__ = 'rovlink.excomponent_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovExcomponentRelayData)
  ))
_sym_db.RegisterMessage(RovExcomponentRelayData)

RovExcomponentRescueData = _reflection.GeneratedProtocolMessageType('RovExcomponentRescueData', (_message.Message,), dict(
  DESCRIPTOR = _ROVEXCOMPONENTRESCUEDATA,
  __module__ = 'rovlink.excomponent_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovExcomponentRescueData)
  ))
_sym_db.RegisterMessage(RovExcomponentRescueData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
