# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rovlink/excontrol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rovlink/excontrol.proto',
  package='coralreef.api.rovlink',
  syntax='proto3',
  serialized_options=_b('\252\002\025CoralReef.Api.Rovlink'),
  serialized_pb=_b('\n\x17rovlink/excontrol.proto\x12\x15\x63oralreef.api.rovlink\"5\n\x15RovExcontrolClampData\x12\r\n\x05\x63lamp\x18\x01 \x01(\x05\x12\r\n\x05wrist\x18\x02 \x01(\x05\":\n\x14RovExcontrolArmAData\x12\n\n\x02\x61\x31\x18\x01 \x01(\r\x12\n\n\x02\x61\x32\x18\x02 \x01(\r\x12\n\n\x02\x61\x33\x18\x03 \x01(\r\":\n\x14RovExcontrolArmBData\x12\n\n\x02\x62\x31\x18\x01 \x01(\r\x12\n\n\x02\x62\x32\x18\x02 \x01(\r\x12\n\n\x02\x62\x33\x18\x03 \x01(\r\":\n\x14RovExcontrolArmCData\x12\n\n\x02\x63\x31\x18\x01 \x01(\r\x12\n\n\x02\x63\x32\x18\x02 \x01(\r\x12\n\n\x02\x63\x33\x18\x03 \x01(\rB\x18\xaa\x02\x15\x43oralReef.Api.Rovlinkb\x06proto3')
)




_ROVEXCONTROLCLAMPDATA = _descriptor.Descriptor(
  name='RovExcontrolClampData',
  full_name='coralreef.api.rovlink.RovExcontrolClampData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clamp', full_name='coralreef.api.rovlink.RovExcontrolClampData.clamp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wrist', full_name='coralreef.api.rovlink.RovExcontrolClampData.wrist', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=103,
)


_ROVEXCONTROLARMADATA = _descriptor.Descriptor(
  name='RovExcontrolArmAData',
  full_name='coralreef.api.rovlink.RovExcontrolArmAData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a1', full_name='coralreef.api.rovlink.RovExcontrolArmAData.a1', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='a2', full_name='coralreef.api.rovlink.RovExcontrolArmAData.a2', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='a3', full_name='coralreef.api.rovlink.RovExcontrolArmAData.a3', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=163,
)


_ROVEXCONTROLARMBDATA = _descriptor.Descriptor(
  name='RovExcontrolArmBData',
  full_name='coralreef.api.rovlink.RovExcontrolArmBData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='b1', full_name='coralreef.api.rovlink.RovExcontrolArmBData.b1', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b2', full_name='coralreef.api.rovlink.RovExcontrolArmBData.b2', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b3', full_name='coralreef.api.rovlink.RovExcontrolArmBData.b3', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=223,
)


_ROVEXCONTROLARMCDATA = _descriptor.Descriptor(
  name='RovExcontrolArmCData',
  full_name='coralreef.api.rovlink.RovExcontrolArmCData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='c1', full_name='coralreef.api.rovlink.RovExcontrolArmCData.c1', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c2', full_name='coralreef.api.rovlink.RovExcontrolArmCData.c2', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c3', full_name='coralreef.api.rovlink.RovExcontrolArmCData.c3', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=283,
)

DESCRIPTOR.message_types_by_name['RovExcontrolClampData'] = _ROVEXCONTROLCLAMPDATA
DESCRIPTOR.message_types_by_name['RovExcontrolArmAData'] = _ROVEXCONTROLARMADATA
DESCRIPTOR.message_types_by_name['RovExcontrolArmBData'] = _ROVEXCONTROLARMBDATA
DESCRIPTOR.message_types_by_name['RovExcontrolArmCData'] = _ROVEXCONTROLARMCDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RovExcontrolClampData = _reflection.GeneratedProtocolMessageType('RovExcontrolClampData', (_message.Message,), dict(
  DESCRIPTOR = _ROVEXCONTROLCLAMPDATA,
  __module__ = 'rovlink.excontrol_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovExcontrolClampData)
  ))
_sym_db.RegisterMessage(RovExcontrolClampData)

RovExcontrolArmAData = _reflection.GeneratedProtocolMessageType('RovExcontrolArmAData', (_message.Message,), dict(
  DESCRIPTOR = _ROVEXCONTROLARMADATA,
  __module__ = 'rovlink.excontrol_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovExcontrolArmAData)
  ))
_sym_db.RegisterMessage(RovExcontrolArmAData)

RovExcontrolArmBData = _reflection.GeneratedProtocolMessageType('RovExcontrolArmBData', (_message.Message,), dict(
  DESCRIPTOR = _ROVEXCONTROLARMBDATA,
  __module__ = 'rovlink.excontrol_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovExcontrolArmBData)
  ))
_sym_db.RegisterMessage(RovExcontrolArmBData)

RovExcontrolArmCData = _reflection.GeneratedProtocolMessageType('RovExcontrolArmCData', (_message.Message,), dict(
  DESCRIPTOR = _ROVEXCONTROLARMCDATA,
  __module__ = 'rovlink.excontrol_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovExcontrolArmCData)
  ))
_sym_db.RegisterMessage(RovExcontrolArmCData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
