# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rovlink/exdata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rovlink/exdata.proto',
  package='coralreef.api.rovlink',
  syntax='proto3',
  serialized_options=_b('\252\002\025CoralReef.Api.Rovlink'),
  serialized_pb=_b('\n\x14rovlink/exdata.proto\x12\x15\x63oralreef.api.rovlink\"\'\n\x14RovExdataLeakageData\x12\x0f\n\x07leakage\x18\x01 \x01(\x04\"l\n\x16RovExdataKeepAliveData\x12\x11\n\ttimestamp\x18\x01 \x01(\r\x12?\n\x06status\x18\x02 \x01(\x0e\x32/.coralreef.api.rovlink.RovExdataKeepAliveStatus*=\n\x18RovExdataKeepAliveStatus\x12\x0b\n\x07HEALTHY\x10\x00\x12\x14\n\x10WATCHDOG_TIMEOUT\x10\x01\x42\x18\xaa\x02\x15\x43oralReef.Api.Rovlinkb\x06proto3')
)

_ROVEXDATAKEEPALIVESTATUS = _descriptor.EnumDescriptor(
  name='RovExdataKeepAliveStatus',
  full_name='coralreef.api.rovlink.RovExdataKeepAliveStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HEALTHY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WATCHDOG_TIMEOUT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=198,
  serialized_end=259,
)
_sym_db.RegisterEnumDescriptor(_ROVEXDATAKEEPALIVESTATUS)

RovExdataKeepAliveStatus = enum_type_wrapper.EnumTypeWrapper(_ROVEXDATAKEEPALIVESTATUS)
HEALTHY = 0
WATCHDOG_TIMEOUT = 1



_ROVEXDATALEAKAGEDATA = _descriptor.Descriptor(
  name='RovExdataLeakageData',
  full_name='coralreef.api.rovlink.RovExdataLeakageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='leakage', full_name='coralreef.api.rovlink.RovExdataLeakageData.leakage', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=86,
)


_ROVEXDATAKEEPALIVEDATA = _descriptor.Descriptor(
  name='RovExdataKeepAliveData',
  full_name='coralreef.api.rovlink.RovExdataKeepAliveData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='coralreef.api.rovlink.RovExdataKeepAliveData.timestamp', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='coralreef.api.rovlink.RovExdataKeepAliveData.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=196,
)

_ROVEXDATAKEEPALIVEDATA.fields_by_name['status'].enum_type = _ROVEXDATAKEEPALIVESTATUS
DESCRIPTOR.message_types_by_name['RovExdataLeakageData'] = _ROVEXDATALEAKAGEDATA
DESCRIPTOR.message_types_by_name['RovExdataKeepAliveData'] = _ROVEXDATAKEEPALIVEDATA
DESCRIPTOR.enum_types_by_name['RovExdataKeepAliveStatus'] = _ROVEXDATAKEEPALIVESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RovExdataLeakageData = _reflection.GeneratedProtocolMessageType('RovExdataLeakageData', (_message.Message,), dict(
  DESCRIPTOR = _ROVEXDATALEAKAGEDATA,
  __module__ = 'rovlink.exdata_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovExdataLeakageData)
  ))
_sym_db.RegisterMessage(RovExdataLeakageData)

RovExdataKeepAliveData = _reflection.GeneratedProtocolMessageType('RovExdataKeepAliveData', (_message.Message,), dict(
  DESCRIPTOR = _ROVEXDATAKEEPALIVEDATA,
  __module__ = 'rovlink.exdata_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovExdataKeepAliveData)
  ))
_sym_db.RegisterMessage(RovExdataKeepAliveData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
