# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rovlink/host.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rovlink/host.proto',
  package='coralreef.api.rovlink',
  syntax='proto3',
  serialized_options=_b('\252\002\025CoralReef.Api.Rovlink'),
  serialized_pb=_b('\n\x12rovlink/host.proto\x12\x15\x63oralreef.api.rovlink\"I\n\x11RovHostCamaraData\x12\x34\n\x06\x63\x61mara\x18\x01 \x03(\x0e\x32$.coralreef.api.rovlink.RovCamaraType*8\n\rRovCamaraType\x12\n\n\x06NO_CAM\x10\x00\x12\r\n\tFRONT_CAM\x10\x01\x12\x0c\n\x08\x42\x41\x43K_CAM\x10\x02\x42\x18\xaa\x02\x15\x43oralReef.Api.Rovlinkb\x06proto3')
)

_ROVCAMARATYPE = _descriptor.EnumDescriptor(
  name='RovCamaraType',
  full_name='coralreef.api.rovlink.RovCamaraType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_CAM', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRONT_CAM', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BACK_CAM', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=120,
  serialized_end=176,
)
_sym_db.RegisterEnumDescriptor(_ROVCAMARATYPE)

RovCamaraType = enum_type_wrapper.EnumTypeWrapper(_ROVCAMARATYPE)
NO_CAM = 0
FRONT_CAM = 1
BACK_CAM = 2



_ROVHOSTCAMARADATA = _descriptor.Descriptor(
  name='RovHostCamaraData',
  full_name='coralreef.api.rovlink.RovHostCamaraData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='camara', full_name='coralreef.api.rovlink.RovHostCamaraData.camara', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=118,
)

_ROVHOSTCAMARADATA.fields_by_name['camara'].enum_type = _ROVCAMARATYPE
DESCRIPTOR.message_types_by_name['RovHostCamaraData'] = _ROVHOSTCAMARADATA
DESCRIPTOR.enum_types_by_name['RovCamaraType'] = _ROVCAMARATYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RovHostCamaraData = _reflection.GeneratedProtocolMessageType('RovHostCamaraData', (_message.Message,), dict(
  DESCRIPTOR = _ROVHOSTCAMARADATA,
  __module__ = 'rovlink.host_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovHostCamaraData)
  ))
_sym_db.RegisterMessage(RovHostCamaraData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
