# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rovlink/mode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rovlink/mode.proto',
  package='coralreef.api.rovlink',
  syntax='proto3',
  serialized_options=_b('\252\002\025CoralReef.Api.Rovlink'),
  serialized_pb=_b('\n\x12rovlink/mode.proto\x12\x15\x63oralreef.api.rovlink\"t\n\x10RovModeModeAData\x12\x11\n\tside_push\x18\x01 \x01(\x08\x12\x0c\n\x04tilt\x18\x02 \x01(\x08\x12\x0c\n\x04roll\x18\x03 \x01(\x08\x12\x11\n\tauxiliary\x18\x04 \x01(\x08\x12\x0e\n\x06rescue\x18\x05 \x01(\x08\x12\x0e\n\x06module\x18\x06 \x01(\x08\"\xa2\x01\n\x10RovModeModeBData\x12\x14\n\x0ckeep_heading\x18\x01 \x01(\x08\x12\x12\n\nkeep_depth\x18\x02 \x01(\x08\x12\x16\n\x0e\x61uto_stabilize\x18\x03 \x01(\x08\x12\x15\n\rauto_schedule\x18\x04 \x01(\x08\x12\x14\n\x0c\x61uto_execute\x18\x05 \x01(\x08\x12\x1f\n\x17\x61uto_avoiding_obstacles\x18\x06 \x01(\x08\x42\x18\xaa\x02\x15\x43oralReef.Api.Rovlinkb\x06proto3')
)




_ROVMODEMODEADATA = _descriptor.Descriptor(
  name='RovModeModeAData',
  full_name='coralreef.api.rovlink.RovModeModeAData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='side_push', full_name='coralreef.api.rovlink.RovModeModeAData.side_push', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tilt', full_name='coralreef.api.rovlink.RovModeModeAData.tilt', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roll', full_name='coralreef.api.rovlink.RovModeModeAData.roll', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auxiliary', full_name='coralreef.api.rovlink.RovModeModeAData.auxiliary', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rescue', full_name='coralreef.api.rovlink.RovModeModeAData.rescue', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='module', full_name='coralreef.api.rovlink.RovModeModeAData.module', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=161,
)


_ROVMODEMODEBDATA = _descriptor.Descriptor(
  name='RovModeModeBData',
  full_name='coralreef.api.rovlink.RovModeModeBData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keep_heading', full_name='coralreef.api.rovlink.RovModeModeBData.keep_heading', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keep_depth', full_name='coralreef.api.rovlink.RovModeModeBData.keep_depth', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auto_stabilize', full_name='coralreef.api.rovlink.RovModeModeBData.auto_stabilize', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auto_schedule', full_name='coralreef.api.rovlink.RovModeModeBData.auto_schedule', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auto_execute', full_name='coralreef.api.rovlink.RovModeModeBData.auto_execute', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auto_avoiding_obstacles', full_name='coralreef.api.rovlink.RovModeModeBData.auto_avoiding_obstacles', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=326,
)

DESCRIPTOR.message_types_by_name['RovModeModeAData'] = _ROVMODEMODEADATA
DESCRIPTOR.message_types_by_name['RovModeModeBData'] = _ROVMODEMODEBDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RovModeModeAData = _reflection.GeneratedProtocolMessageType('RovModeModeAData', (_message.Message,), dict(
  DESCRIPTOR = _ROVMODEMODEADATA,
  __module__ = 'rovlink.mode_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovModeModeAData)
  ))
_sym_db.RegisterMessage(RovModeModeAData)

RovModeModeBData = _reflection.GeneratedProtocolMessageType('RovModeModeBData', (_message.Message,), dict(
  DESCRIPTOR = _ROVMODEMODEBDATA,
  __module__ = 'rovlink.mode_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovModeModeBData)
  ))
_sym_db.RegisterMessage(RovModeModeBData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
