# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rovlink/sensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rovlink/sensor.proto',
  package='coralreef.api.rovlink',
  syntax='proto3',
  serialized_options=_b('\252\002\025CoralReef.Api.Rovlink'),
  serialized_pb=_b('\n\x14rovlink/sensor.proto\x12\x15\x63oralreef.api.rovlink\"Y\n\x1eRovSensorCabTempHumidPressData\x12\x13\n\x0btemperature\x18\x01 \x01(\r\x12\x10\n\x08humidity\x18\x02 \x01(\r\x12\x10\n\x08pressure\x18\x03 \x01(\r\"X\n RovSensorWaterTempDepthPressData\x12\x13\n\x0btemperature\x18\x01 \x01(\r\x12\r\n\x05\x64\x65pth\x18\x02 \x01(\r\x12\x10\n\x08pressure\x18\x03 \x01(\r\"<\n\x19RovSensorAccelerationData\x12\t\n\x01x\x18\x01 \x01(\r\x12\t\n\x01y\x18\x02 \x01(\r\x12\t\n\x01z\x18\x03 \x01(\r\"?\n\x1cRovSensorAngularVelocityData\x12\t\n\x01x\x18\x01 \x01(\r\x12\t\n\x01y\x18\x02 \x01(\r\x12\t\n\x01z\x18\x03 \x01(\r\"C\n\x17RovSensorEulerAngleData\x12\r\n\x05pitch\x18\x01 \x01(\x05\x12\x0c\n\x04roll\x18\x02 \x01(\x05\x12\x0b\n\x03yaw\x18\x03 \x01(\r\"=\n\x1aRovSensorMagneticFieldData\x12\t\n\x01x\x18\x01 \x01(\r\x12\t\n\x01y\x18\x02 \x01(\r\x12\t\n\x01z\x18\x03 \x01(\r\">\n\x18RovSensorHeightSonarData\x12\x0e\n\x06height\x18\x01 \x01(\r\x12\x12\n\nconfidence\x18\x02 \x01(\r\"B\n\x1aRovSensorDistanceSonarData\x12\x10\n\x08\x64istance\x18\x01 \x01(\r\x12\x12\n\nconfidence\x18\x02 \x01(\rB\x18\xaa\x02\x15\x43oralReef.Api.Rovlinkb\x06proto3')
)




_ROVSENSORCABTEMPHUMIDPRESSDATA = _descriptor.Descriptor(
  name='RovSensorCabTempHumidPressData',
  full_name='coralreef.api.rovlink.RovSensorCabTempHumidPressData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='coralreef.api.rovlink.RovSensorCabTempHumidPressData.temperature', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='coralreef.api.rovlink.RovSensorCabTempHumidPressData.humidity', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pressure', full_name='coralreef.api.rovlink.RovSensorCabTempHumidPressData.pressure', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=136,
)


_ROVSENSORWATERTEMPDEPTHPRESSDATA = _descriptor.Descriptor(
  name='RovSensorWaterTempDepthPressData',
  full_name='coralreef.api.rovlink.RovSensorWaterTempDepthPressData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='coralreef.api.rovlink.RovSensorWaterTempDepthPressData.temperature', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth', full_name='coralreef.api.rovlink.RovSensorWaterTempDepthPressData.depth', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pressure', full_name='coralreef.api.rovlink.RovSensorWaterTempDepthPressData.pressure', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=226,
)


_ROVSENSORACCELERATIONDATA = _descriptor.Descriptor(
  name='RovSensorAccelerationData',
  full_name='coralreef.api.rovlink.RovSensorAccelerationData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='coralreef.api.rovlink.RovSensorAccelerationData.x', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='coralreef.api.rovlink.RovSensorAccelerationData.y', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='coralreef.api.rovlink.RovSensorAccelerationData.z', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=288,
)


_ROVSENSORANGULARVELOCITYDATA = _descriptor.Descriptor(
  name='RovSensorAngularVelocityData',
  full_name='coralreef.api.rovlink.RovSensorAngularVelocityData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='coralreef.api.rovlink.RovSensorAngularVelocityData.x', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='coralreef.api.rovlink.RovSensorAngularVelocityData.y', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='coralreef.api.rovlink.RovSensorAngularVelocityData.z', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=353,
)


_ROVSENSOREULERANGLEDATA = _descriptor.Descriptor(
  name='RovSensorEulerAngleData',
  full_name='coralreef.api.rovlink.RovSensorEulerAngleData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pitch', full_name='coralreef.api.rovlink.RovSensorEulerAngleData.pitch', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roll', full_name='coralreef.api.rovlink.RovSensorEulerAngleData.roll', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='coralreef.api.rovlink.RovSensorEulerAngleData.yaw', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=422,
)


_ROVSENSORMAGNETICFIELDDATA = _descriptor.Descriptor(
  name='RovSensorMagneticFieldData',
  full_name='coralreef.api.rovlink.RovSensorMagneticFieldData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='coralreef.api.rovlink.RovSensorMagneticFieldData.x', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='coralreef.api.rovlink.RovSensorMagneticFieldData.y', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='coralreef.api.rovlink.RovSensorMagneticFieldData.z', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=485,
)


_ROVSENSORHEIGHTSONARDATA = _descriptor.Descriptor(
  name='RovSensorHeightSonarData',
  full_name='coralreef.api.rovlink.RovSensorHeightSonarData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='coralreef.api.rovlink.RovSensorHeightSonarData.height', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='coralreef.api.rovlink.RovSensorHeightSonarData.confidence', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=487,
  serialized_end=549,
)


_ROVSENSORDISTANCESONARDATA = _descriptor.Descriptor(
  name='RovSensorDistanceSonarData',
  full_name='coralreef.api.rovlink.RovSensorDistanceSonarData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='distance', full_name='coralreef.api.rovlink.RovSensorDistanceSonarData.distance', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='coralreef.api.rovlink.RovSensorDistanceSonarData.confidence', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=551,
  serialized_end=617,
)

DESCRIPTOR.message_types_by_name['RovSensorCabTempHumidPressData'] = _ROVSENSORCABTEMPHUMIDPRESSDATA
DESCRIPTOR.message_types_by_name['RovSensorWaterTempDepthPressData'] = _ROVSENSORWATERTEMPDEPTHPRESSDATA
DESCRIPTOR.message_types_by_name['RovSensorAccelerationData'] = _ROVSENSORACCELERATIONDATA
DESCRIPTOR.message_types_by_name['RovSensorAngularVelocityData'] = _ROVSENSORANGULARVELOCITYDATA
DESCRIPTOR.message_types_by_name['RovSensorEulerAngleData'] = _ROVSENSOREULERANGLEDATA
DESCRIPTOR.message_types_by_name['RovSensorMagneticFieldData'] = _ROVSENSORMAGNETICFIELDDATA
DESCRIPTOR.message_types_by_name['RovSensorHeightSonarData'] = _ROVSENSORHEIGHTSONARDATA
DESCRIPTOR.message_types_by_name['RovSensorDistanceSonarData'] = _ROVSENSORDISTANCESONARDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RovSensorCabTempHumidPressData = _reflection.GeneratedProtocolMessageType('RovSensorCabTempHumidPressData', (_message.Message,), dict(
  DESCRIPTOR = _ROVSENSORCABTEMPHUMIDPRESSDATA,
  __module__ = 'rovlink.sensor_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovSensorCabTempHumidPressData)
  ))
_sym_db.RegisterMessage(RovSensorCabTempHumidPressData)

RovSensorWaterTempDepthPressData = _reflection.GeneratedProtocolMessageType('RovSensorWaterTempDepthPressData', (_message.Message,), dict(
  DESCRIPTOR = _ROVSENSORWATERTEMPDEPTHPRESSDATA,
  __module__ = 'rovlink.sensor_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovSensorWaterTempDepthPressData)
  ))
_sym_db.RegisterMessage(RovSensorWaterTempDepthPressData)

RovSensorAccelerationData = _reflection.GeneratedProtocolMessageType('RovSensorAccelerationData', (_message.Message,), dict(
  DESCRIPTOR = _ROVSENSORACCELERATIONDATA,
  __module__ = 'rovlink.sensor_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovSensorAccelerationData)
  ))
_sym_db.RegisterMessage(RovSensorAccelerationData)

RovSensorAngularVelocityData = _reflection.GeneratedProtocolMessageType('RovSensorAngularVelocityData', (_message.Message,), dict(
  DESCRIPTOR = _ROVSENSORANGULARVELOCITYDATA,
  __module__ = 'rovlink.sensor_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovSensorAngularVelocityData)
  ))
_sym_db.RegisterMessage(RovSensorAngularVelocityData)

RovSensorEulerAngleData = _reflection.GeneratedProtocolMessageType('RovSensorEulerAngleData', (_message.Message,), dict(
  DESCRIPTOR = _ROVSENSOREULERANGLEDATA,
  __module__ = 'rovlink.sensor_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovSensorEulerAngleData)
  ))
_sym_db.RegisterMessage(RovSensorEulerAngleData)

RovSensorMagneticFieldData = _reflection.GeneratedProtocolMessageType('RovSensorMagneticFieldData', (_message.Message,), dict(
  DESCRIPTOR = _ROVSENSORMAGNETICFIELDDATA,
  __module__ = 'rovlink.sensor_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovSensorMagneticFieldData)
  ))
_sym_db.RegisterMessage(RovSensorMagneticFieldData)

RovSensorHeightSonarData = _reflection.GeneratedProtocolMessageType('RovSensorHeightSonarData', (_message.Message,), dict(
  DESCRIPTOR = _ROVSENSORHEIGHTSONARDATA,
  __module__ = 'rovlink.sensor_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovSensorHeightSonarData)
  ))
_sym_db.RegisterMessage(RovSensorHeightSonarData)

RovSensorDistanceSonarData = _reflection.GeneratedProtocolMessageType('RovSensorDistanceSonarData', (_message.Message,), dict(
  DESCRIPTOR = _ROVSENSORDISTANCESONARDATA,
  __module__ = 'rovlink.sensor_pb2'
  # @@protoc_insertion_point(class_scope:coralreef.api.rovlink.RovSensorDistanceSonarData)
  ))
_sym_db.RegisterMessage(RovSensorDistanceSonarData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
